name: Publish Storybook

on:
  push:
    branches: [ master ]
    paths:
      - '.storybook/**'
      - 'stories/**'
      - 'scss/**'
      - '.github/workflows/storybook.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: Install Dependencies
      run: npm ci
    - name: Build Storybook
      run: npm run build-storybook
    - name: Deploy GH Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
