name: Publish Templates

on:
  push:
    branches: [ master ]
    paths:
      - 'templates/**'
      - 'scss/**'
      - '.github/workflows/templates.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 22.x
    - name: Install Dependencies
      run: npm ci
    - name: Publish to Commerble
      env:
          CBAPI_ENDPOINT: ${{ secrets.CBAPI_ENDPOINT }}
          CBAPI_USERNAME: ${{ secrets.CBAPI_USERNAME }}
          CBAPI_PASSWORD: ${{ secrets.CBAPI_PASSWORD }}
      run: npm run publish
